# Generated by Django 5.2.6 on 2025-09-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_managers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='List',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
