# Generated by Django 5.2.6 on 2025-09-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_managers', '0002_rename_lists_list_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delivery_date',
        ),
    ]
