# Generated by Django 5.2.6 on 2025-09-19 19:35

import django.db.models.deletion
import task_managers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_managers', '0003_remove_task_delivery_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[task_managers.models.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[task_managers.models.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[task_managers.models.validate_deadline]),
        ),
    ]
