# Generated by Django 5.2.6 on 2025-09-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_managers', '0004_rename_text_task_description_remove_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('to-do', 'A fazer'), ('doing', 'Fazendo'), ('done', 'Feito')], default='to-do', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('to-do', 'A fazer'), ('doing', 'Fazendo'), ('done', 'Feito')], default='to-do', max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='task_managers.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_managers.list'),
        ),
    ]
