# Generated by Django 5.2.6 on 2025-09-19 22:41

import task_managers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_managers', '0005_list_status_project_status_alter_list_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[task_managers.models.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[task_managers.models.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[task_managers.models.validate_deadline]),
        ),
    ]
